server {
    listen 80;
    server_name _;   # acepta cualquier host o dominio

    root /usr/share/nginx/html;
    index index.html;

    # Servir archivos estáticos del frontend
    location / {
        try_files $uri /index.html;
    }

    # Redirigir peticiones de API al backend
    location /api/ {
        proxy_pass http://backend-service:80;   # 👈 usa el puerto expuesto por el Service
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
